apiVersion: v1
kind: Pod
metadata:
  name: kptunnel-{tunnel_id}
  labels:
    app: kptunnel
    tunnel: {tunnel_id}
spec:
  containers:
  - name: kptunnel
    image: kptunnel
    command:
      - /kptunnel
      - r-wsserver
      - :1234
      - :{listen_port},{forward_to_host}:{forward_to_port}
    ports:
    - containerPort: 1234
    - containerPort: {listen_port}
    imagePullPolicy: IfNotPresent
    livenessProbe:
      tcpSocket:
        port: 1234
      initialDelaySeconds: 5
      periodSeconds: 5
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: {ws_service_name}
  labels:
    tunnel: {tunnel_id}
spec:
  selector:
    app: kptunnel
    tunnel: {tunnel_id}
  ports:
    - port: 1234
      targetPort: 1234
---
apiVersion: v1
kind: Service
metadata:
  name: {tun_service_name}
  labels:
    tunnel: {tunnel_id}
spec:
  type: NodePort
  selector:
    app: kptunnel
    tunnel: {tunnel_id}
  ports:
    - port: {listen_port}
      targetPort: {listen_port}
